// go-data-sync applies a sync SQL file generated by go-data-checksum
// (--generate-sync-sql) to the target MySQL instance.
//
// Safety model:
//   - Dry-run by default: shows what would be applied; nothing is executed
//     unless --execute is passed.
//   - Only REPLACE INTO statements are accepted; anything else in the file
//     aborts the run before a single statement is executed.
//   - Statements are applied in transactional batches; a failed batch is
//     rolled back and the run stops with a precise error location.
package main

import (
	"bufio"
	gosql "database/sql"
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"
	"sync"
	"sync/atomic"
	"syscall" // For checking EPIPE
	"time"

	"github.com/go-sql-driver/mysql"
	_ "github.com/go-sql-driver/mysql"
)

var AppVersion string

var replaceIntoTablePattern = regexp.MustCompile("(?i)^REPLACE\\s+INTO\\s+(`[^`]+`\\.`[^`]+`|\\S+)")

type syncStatement struct {
	lineNumber int
	table      string
	sql        string
}

func parseSyncFile(path string) ([]syncStatement, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("cannot open sync SQL file: %v", err)
	}
	defer file.Close()

	var statements []syncStatement
	scanner := bufio.NewScanner(file)
	// Allow long rows: default bufio limit is 64KB, raise to 16MB.
	scanner.Buffer(make([]byte, 0, 1024*1024), 16*1024*1024)

	lineNumber := 0
	for scanner.Scan() {
		lineNumber++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "--") {
			continue
		}
		match := replaceIntoTablePattern.FindStringSubmatch(line)
		if match == nil {
			return nil, fmt.Errorf("line %d: only REPLACE INTO statements are allowed, found: %.80s", lineNumber, line)
		}
		if !strings.HasSuffix(line, ";") {
			return nil, fmt.Errorf("line %d: statement does not end with ';' (multi-line statements are not supported): %.80s", lineNumber, line)
		}
		statements = append(statements, syncStatement{
			lineNumber: lineNumber,
			table:      match[1],
			sql:        strings.TrimSuffix(line, ";"),
		})
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("failed reading sync SQL file: %v", err)
	}
	return statements, nil
}

func summarize(statements []syncStatement) {
	perTable := make(map[string]int)
	var tables []string
	for _, stmt := range statements {
		if perTable[stmt.table] == 0 {
			tables = append(tables, stmt.table)
		}
		perTable[stmt.table]++
	}
	fmt.Printf("Sync file contains %d REPLACE INTO statements across %d table(s):\n", len(statements), len(tables))
	for _, table := range tables {
		fmt.Printf("  %s: %d statements\n", table, perTable[table])
	}
}

func apply(db *gosql.DB, statements []syncStatement, batchSize int, threads int, maxRetries int, retryDelay time.Duration) error {
	startTime := time.Now()
	var applied int64
	inserted := int64(0)
	replaced := int64(0)

	type batchJob struct {
		records []syncStatement
	}

	numStatements := len(statements)
	jobsChan := make(chan batchJob, (numStatements/batchSize)+1)
	for batchStart := 0; batchStart < numStatements; batchStart += batchSize {
		batchEnd := batchStart + batchSize
		if batchEnd > numStatements {
			batchEnd = numStatements
		}
		jobsChan <- batchJob{records: statements[batchStart:batchEnd]}
	}
	close(jobsChan)

	if threads > (numStatements/batchSize)+1 {
		threads = (numStatements / batchSize) + 1
	}
	if threads < 1 {
		threads = 1
	}

	var wg sync.WaitGroup
	var once sync.Once
	var firstErr error
	setFirstErr := func(err error) {
		once.Do(func() {
			firstErr = err
		})
	}

	for i := 0; i < threads; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for job := range jobsChan {
				// Retry loop for the entire batch
				for attempt := 0; attempt <= maxRetries; attempt++ {
					if firstErr != nil { // Check if another goroutine already failed
						return
					}

					if attempt > 0 {
						fmt.Printf("Retrying batch for statements %d-%d (attempt %d/%d)...\n", job.records[0].lineNumber, job.records[len(job.records)-1].lineNumber, attempt, maxRetries)
						time.Sleep(retryDelay)
					}

					trx, err := db.Begin()
					if err != nil {
						setFirstErr(fmt.Errorf("failed to begin transaction for batch starting at line %d: %v", job.records[0].lineNumber, err))
						return
					}

					var batchFailed bool
					var localReplaced, localInserted int64
					for _, stmt := range job.records {
						result, err := trx.Exec(stmt.sql)
						if err != nil {
							trx.Rollback()
							// Check for retryable errors.
							// ER_NO_SUCH_TABLE (1146) is retryable if it's transient (e.g., DDL interference).
							// ER_LOCK_DEADLOCK (1213) and ER_LOCK_WAIT_TIMEOUT (1205) are common retryable errors.
							// EPIPE (broken pipe) can indicate a lost connection.
							if isRetryableError(err) && attempt < maxRetries {
								batchFailed = true
								break // Break from inner loop, retry outer loop (the batch)
							} else {
								setFirstErr(fmt.Errorf("statement at line %d failed (batch rolled back): %v", stmt.lineNumber, err))
								return
							}
						}
						if rowsAffected, err := result.RowsAffected(); err == nil && rowsAffected >= 2 {
							localReplaced++
						} else {
							localInserted++
						}
					}

					if batchFailed {
						continue // Retry the current batch
					}

					if err := trx.Commit(); err != nil {
						if isRetryableError(err) && attempt < maxRetries { // Commit can also fail transiently
							batchFailed = true
							continue // Retry the current batch
						}
						setFirstErr(fmt.Errorf("failed to commit batch ending at line %d: %v", job.records[len(job.records)-1].lineNumber, err))
						return
					}

					// If we reached here, the batch was successful, break retry loop
					atomic.AddInt64(&replaced, localReplaced)
					atomic.AddInt64(&inserted, localInserted)
					currentApplied := atomic.AddInt64(&applied, int64(len(job.records)))
					previousApplied := currentApplied - int64(len(job.records))

					crossedBoundary := (currentApplied / 10000) > (previousApplied / 10000)
					isLast := currentApplied == int64(numStatements)
					if (crossedBoundary && !isLast) || isLast {
						fmt.Printf("Applied %d/%d statements...\n", currentApplied, numStatements)
					}
					break // Batch successful, move to next job
				}
			}
		}()
	}
	wg.Wait()

	if firstErr != nil {
		return firstErr
	}

	fmt.Printf("Done: %d statements applied in %v (%d rows inserted, %d rows replaced).\n",
		applied, time.Since(startTime).Round(time.Millisecond), inserted, replaced)
	return nil
}

// isRetryableError checks if the given error is transient and should trigger a retry.
func isRetryableError(err error) bool {
	if err == nil {
		return false
	}
	// Check for MySQL specific errors
	if mysqlErr, ok := err.(*mysql.MySQLError); ok {
		switch mysqlErr.Number {
		case 1146, // ER_NO_SUCH_TABLE - can be transient if DDL is happening
			1205, // ER_LOCK_WAIT_TIMEOUT
			1213: // ER_LOCK_DEADLOCK
			return true
		}
	}
	// Check for network errors like broken pipe
	return strings.Contains(err.Error(), syscall.EPIPE.Error())
}

func main() {
	sqlFile := flag.String("sql-file", "", "Sync SQL file generated by go-data-checksum --generate-sync-sql (required)")
	host := flag.String("target-db-host", "127.0.0.1", "Target MySQL hostname")
	port := flag.Int("target-db-port", 3306, "Target MySQL port")
	user := flag.String("target-db-user", "", "Target MySQL user")
	password := flag.String("target-db-password", "", "Target MySQL password")
	timeout := flag.Int("conn-db-timeout", 60, "connect db timeout in seconds")
	execute := flag.Bool("execute", false, "Actually apply the statements. Without this flag the tool runs in dry-run mode.")
	batchSize := flag.Int("batch-size", 100, "Number of statements per transaction")
	threads := flag.Int("threads", 4, "Number of concurrent threads to apply statements")
	maxRetries := flag.Int("max-retries", 0, "Maximum number of times to retry a failed batch (default 0, no retries)")
	retryDelay := flag.Duration("retry-delay", 1*time.Second, "Delay between retries for a failed batch")
	skipBinlog := flag.Bool("skip-binlog", false, "Set @@session.sql_log_bin = 0 on target connection")
	skipFK := flag.Bool("skip-fk-checks", false, "Set @@session.foreign_key_checks = 0 on target connection")
	skipUnique := flag.Bool("skip-unique-checks", false, "Set @@session.unique_checks = 0 on target connection")
	version := flag.Bool("version", false, "Print version & exit")
	flag.Parse()

	if *version {
		appVersion := AppVersion
		if appVersion == "" {
			appVersion = "unversioned"
		}
		fmt.Println(appVersion)
		return
	}

	fail := func(format string, args ...interface{}) {
		fmt.Fprintf(os.Stderr, "Error: "+format+"\n", args...)
		os.Exit(1)
	}

	if *sqlFile == "" {
		fail("--sql-file is required")
	}
	if *batchSize < 1 {
		*batchSize = 1
	}

	statements, err := parseSyncFile(*sqlFile)
	if err != nil {
		fail("%v", err)
	}
	if len(statements) == 0 {
		fmt.Println("Sync file contains no statements; nothing to do.")
		return
	}

	summarize(statements)

	if !*execute {
		fmt.Println("\nDRY-RUN mode: no changes applied. First statements that would run:")
		previewCount := 5
		if previewCount > len(statements) {
			previewCount = len(statements)
		}
		for _, stmt := range statements[:previewCount] {
			fmt.Printf("  line %d: %.120s\n", stmt.lineNumber, stmt.sql)
		}
		fmt.Println("\nRe-run with --execute to apply. Review the file and back up the target first.")
		return
	}

	// Statements are fully qualified (`db`.`table`), so no default schema is needed.
	dsn := fmt.Sprintf("%s:%s@tcp(%s:%d)/?timeout=%ds&readTimeout=%ds&writeTimeout=%ds&charset=utf8mb4",
		*user, *password, *host, *port, *timeout, *timeout, *timeout)
	db, err := gosql.Open("mysql", dsn)
	if err != nil {
		fail("cannot open target connection: %v", err)
	}
	defer db.Close()
	if err := db.Ping(); err != nil {
		fail("cannot connect to target %s:%d: %v", *host, *port, err)
	}

	db.SetMaxOpenConns(*threads + 2)
	db.SetMaxIdleConns(*threads + 2)

	fmt.Printf("Applying %d statements to %s:%d (batch size %d, threads %d)...\n", len(statements), *host, *port, *batchSize, *threads)

	// Apply session optimizations if requested
	if *skipBinlog {
		if _, err := db.Exec("SET @@session.sql_log_bin = 0;"); err != nil {
			fail("failed to disable binary logging: %v (does your user have SYSTEM_VARIABLES_ADMIN/SUPER?)", err)
		}
		fmt.Println("Session binary logging disabled.")
	}
	if *skipUnique {
		if _, err := db.Exec("SET @@session.unique_checks = 0;"); err != nil {
			fail("failed to disable unique checks: %v", err)
		}
		fmt.Println("Session unique checks disabled.")
	}
	if *skipFK {
		if _, err := db.Exec("SET @@session.foreign_key_checks = 0;"); err != nil {
			fail("failed to disable foreign key checks: %v", err)
		}
		fmt.Println("Session foreign key checks disabled.")
	}

	if err := apply(db, statements, *batchSize, *threads, *maxRetries, *retryDelay); err != nil {
		fail("%v", err)
	}
}
