// go-data-sync applies a sync SQL file generated by go-data-checksum
// (--generate-sync-sql) to the target MySQL instance.
//
// Safety model:
//   - Dry-run by default: shows what would be applied; nothing is executed
//     unless --execute is passed.
//   - Only REPLACE INTO statements are accepted; anything else in the file
//     aborts the run before a single statement is executed.
//   - Statements are applied in transactional batches; a failed batch is
//     rolled back and the run stops with a precise error location.
package main

import (
	"bufio"
	gosql "database/sql"
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"
	"time"

	_ "github.com/go-sql-driver/mysql"
)

var AppVersion string

var replaceIntoTablePattern = regexp.MustCompile("(?i)^REPLACE\\s+INTO\\s+(`[^`]+`\\.`[^`]+`|\\S+)")

type syncStatement struct {
	lineNumber int
	table      string
	sql        string
}

func parseSyncFile(path string) ([]syncStatement, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("cannot open sync SQL file: %v", err)
	}
	defer file.Close()

	var statements []syncStatement
	scanner := bufio.NewScanner(file)
	// Allow long rows: default bufio limit is 64KB, raise to 16MB.
	scanner.Buffer(make([]byte, 0, 1024*1024), 16*1024*1024)

	lineNumber := 0
	for scanner.Scan() {
		lineNumber++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "--") {
			continue
		}
		match := replaceIntoTablePattern.FindStringSubmatch(line)
		if match == nil {
			return nil, fmt.Errorf("line %d: only REPLACE INTO statements are allowed, found: %.80s", lineNumber, line)
		}
		if !strings.HasSuffix(line, ";") {
			return nil, fmt.Errorf("line %d: statement does not end with ';' (multi-line statements are not supported): %.80s", lineNumber, line)
		}
		statements = append(statements, syncStatement{
			lineNumber: lineNumber,
			table:      match[1],
			sql:        strings.TrimSuffix(line, ";"),
		})
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("failed reading sync SQL file: %v", err)
	}
	return statements, nil
}

func summarize(statements []syncStatement) {
	perTable := make(map[string]int)
	var tables []string
	for _, stmt := range statements {
		if perTable[stmt.table] == 0 {
			tables = append(tables, stmt.table)
		}
		perTable[stmt.table]++
	}
	fmt.Printf("Sync file contains %d REPLACE INTO statements across %d table(s):\n", len(statements), len(tables))
	for _, table := range tables {
		fmt.Printf("  %s: %d statements\n", table, perTable[table])
	}
}

func apply(db *gosql.DB, statements []syncStatement, batchSize int) error {
	startTime := time.Now()
	applied := 0
	inserted := int64(0)
	replaced := int64(0)

	for batchStart := 0; batchStart < len(statements); batchStart += batchSize {
		batchEnd := batchStart + batchSize
		if batchEnd > len(statements) {
			batchEnd = len(statements)
		}
		batch := statements[batchStart:batchEnd]

		trx, err := db.Begin()
		if err != nil {
			return fmt.Errorf("failed to begin transaction: %v", err)
		}
		for _, stmt := range batch {
			result, err := trx.Exec(stmt.sql)
			if err != nil {
				trx.Rollback()
				return fmt.Errorf("statement at line %d failed (batch rolled back, %d statements applied so far): %v",
					stmt.lineNumber, applied, err)
			}
			// REPLACE reports 1 row affected for a plain insert and 2 for
			// delete+insert of an existing row.
			if rowsAffected, err := result.RowsAffected(); err == nil && rowsAffected >= 2 {
				replaced++
			} else {
				inserted++
			}
		}
		if err := trx.Commit(); err != nil {
			return fmt.Errorf("failed to commit batch ending at line %d: %v", batch[len(batch)-1].lineNumber, err)
		}
		applied += len(batch)
		fmt.Printf("Applied %d/%d statements...\n", applied, len(statements))
	}

	fmt.Printf("Done: %d statements applied in %v (%d rows inserted, %d rows replaced).\n",
		applied, time.Since(startTime).Round(time.Millisecond), inserted, replaced)
	return nil
}

func main() {
	sqlFile := flag.String("sql-file", "", "Sync SQL file generated by go-data-checksum --generate-sync-sql (required)")
	host := flag.String("target-db-host", "127.0.0.1", "Target MySQL hostname")
	port := flag.Int("target-db-port", 3306, "Target MySQL port")
	user := flag.String("target-db-user", "", "Target MySQL user")
	password := flag.String("target-db-password", "", "Target MySQL password")
	timeout := flag.Int("conn-db-timeout", 60, "connect db timeout in seconds")
	execute := flag.Bool("execute", false, "Actually apply the statements. Without this flag the tool runs in dry-run mode.")
	batchSize := flag.Int("batch-size", 100, "Number of statements per transaction")
	version := flag.Bool("version", false, "Print version & exit")
	flag.Parse()

	if *version {
		appVersion := AppVersion
		if appVersion == "" {
			appVersion = "unversioned"
		}
		fmt.Println(appVersion)
		return
	}

	fail := func(format string, args ...interface{}) {
		fmt.Fprintf(os.Stderr, "Error: "+format+"\n", args...)
		os.Exit(1)
	}

	if *sqlFile == "" {
		fail("--sql-file is required")
	}
	if *batchSize < 1 {
		*batchSize = 1
	}

	statements, err := parseSyncFile(*sqlFile)
	if err != nil {
		fail("%v", err)
	}
	if len(statements) == 0 {
		fmt.Println("Sync file contains no statements; nothing to do.")
		return
	}

	summarize(statements)

	if !*execute {
		fmt.Println("\nDRY-RUN mode: no changes applied. First statements that would run:")
		previewCount := 5
		if previewCount > len(statements) {
			previewCount = len(statements)
		}
		for _, stmt := range statements[:previewCount] {
			fmt.Printf("  line %d: %.120s\n", stmt.lineNumber, stmt.sql)
		}
		fmt.Println("\nRe-run with --execute to apply. Review the file and back up the target first.")
		return
	}

	// Statements are fully qualified (`db`.`table`), so no default schema is needed.
	dsn := fmt.Sprintf("%s:%s@tcp(%s:%d)/?timeout=%ds&readTimeout=%ds&writeTimeout=%ds&charset=utf8mb4",
		*user, *password, *host, *port, *timeout, *timeout, *timeout)
	db, err := gosql.Open("mysql", dsn)
	if err != nil {
		fail("cannot open target connection: %v", err)
	}
	defer db.Close()
	if err := db.Ping(); err != nil {
		fail("cannot connect to target %s:%d: %v", *host, *port, err)
	}

	fmt.Printf("Applying %d statements to %s:%d (batch size %d)...\n", len(statements), *host, *port, *batchSize)
	if err := apply(db, statements, *batchSize); err != nil {
		fail("%v", err)
	}
}
